const actions = {
  ALGORITHMS: 'ALGORITHMS',
  ALGORITHM_LIST: 'ALGORITHM_LIST',
  ALGORITHM_CREATE: 'ALGORITHM_CREATE',
  ALGORITHM_DELETE: 'ALGORITHM_DELETE',
  ALGORITHM_GET: 'ALGORITHM_GET',
  ALGORITHM_DETAIL: 'ALGORITHM_DETAIL',
  ALGORITHM_UPDATE: 'ALGORITHM_UPDATE',
  ALGORITHM_ERROR: 'ALGORITHM_ERROR',
  list: () => ({
    type: actions.ALGORITHM_LIST
  }),
  detail: id => ({
    type: actions.ALGORITHM_DETAIL,
    id
  })
};
export default actions;
